config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'signup',  to: 'users#new'
  get 'login_top' => 'static_pages#login_top'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get    'adminpage'   => 'static_pages#adminpage'
  get    'help'   => 'static_pages#help'
  get    'ranking' => 'static_pages#ranking'
  get    'summary' => 'static_pages#summary'
  get    'summary_recept_badge_user' => 'static_pages#summary_recept_badge_user'
  get    'summary_value_send' => 'static_pages#summary_value_send'
  get    'summary_value_bumon_send' => 'static_pages#summary_value_bumon_send'

  get 'badgeposts/recepting'
  get 'badgeposts/sending'
  get 'badgeposts/sending_all'
  get 'users/full_index'

  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :bumons
  resources :sessions, only: [:new, :create, :destroy]
  resources :badges
  resources :badgeposts
  resources :mongons
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: [:ranking]
  before_action :logged_in_adminuser, only: [:summary]

  def home
    if logged_in?
      redirect_to :action => "login_top"
    end
  end

  def login_top
    if logged_in?
      @feedbadgeposts = Badgepost.limit(10).where(recept_user_id: current_user.id).where("created_at > ?", 30.days.ago).order(created_at: :desc)
      # 今までに獲得したバッジのグラフ
      @graph_recept = get_graph(current_user.id, "", "ALL_RECEPT")
    end
  end

  # 部門別ランキング
  def ranking
    userjoin = User.arel_table
    badgepostjoin = Badgepost.arel_table
    join_condition = userjoin.join(badgepostjoin, Arel::Nodes::OuterJoin)
                .on(userjoin[:id].eq(badgepostjoin[:sent_user_id])).join_sources
    
    @badgeposts = User.joins(join_condition).group(:bumon_id)
              .select(userjoin[:bumon_id], userjoin[:bumon_id].count.as('cnt'))
                    .where(badgepostjoin[:created_at].gteq Time.now.beginning_of_month)
                    .order('cnt DESC').order(:bumon_id)
    # 辞書用に部門情報を取得
    bumons = Bumon.where(activeflg: true)
    @bumonname_hash = get_name_hash(bumons)
  end

  def summary
    if params[:summary_form] == nil
      # 検索未入力時（初回表示時）
      @form = SummaryForm.new
    else
      set_search_form_params
      
      set_master_data
      
      # 画面で指定された範囲に作成されたBadgepostを集計
      if Rails.env == 'production'
        @sentbadgeposts = Badgepost.select(:sent_user_id, :badge_id, "to_char(created_at, 'yyyymm') AS create_month", "COUNT(*) AS count")
                            .where('created_at >= ?', @form.summary_start_date)
                            .where('created_at <= ?', @form.summary_end_date)
                            .group(:sent_user_id, :badge_id, "to_char(created_at, 'yyyymm')").order('count DESC')
        @receptbadgeposts = Badgepost.select(:recept_user_id, :badge_id, "to_char(created_at, 'yyyymm') AS create_month", "COUNT(*) AS count")
                            .where('created_at >= ?', @form.summary_start_date)
                            .where('created_at <= ?', @form.summary_end_date)
                            .group(:recept_user_id, :badge_id, "to_char(created_at, 'yyyymm')").order('count DESC')
      elsif Rails.env == 'development' or Rails.env == 'test'
        @sentbadgeposts = Badgepost.select(:sent_user_id, :badge_id, "strftime('%Y%m', created_at) AS create_month", "COUNT(*) AS count")
                            .where('created_at >= ?', @form.summary_start_date)
                            .where('created_at <= ?', @form.summary_end_date)
                            .group(:sent_user_id, :badge_id, "strftime('%Y%m', created_at)").order('count DESC')
        @receptbadgeposts = Badgepost.select(:recept_user_id, :badge_id, "strftime('%Y%m', created_at) AS create_month", "COUNT(*) AS count")
                            .where('created_at >= ?', @form.summary_start_date)
                            .where('created_at <= ?', @form.summary_end_date)
                            .group(:recept_user_id, :badge_id, "strftime('%Y%m', created_at)").order('count DESC')
      end
    end
  end

  def summary_recept_badge_user
    if params[:summary_form] == nil
      # 検索未入力時（初回表示時）
      @form = SummaryForm.new
    else
      # 検索欄入力時
      set_search_form_params
      
      # マスター情報関連取得
      set_master_data
      
      @receptbadgeposts = Badgepost.select(:recept_user_id, :badge_id, "COUNT(*) AS count")
                            .where('created_at >= ?', @form.summary_start_date)
                            .where('created_at <= ?', @form.summary_end_date)
                            .group(:recept_user_id, :badge_id)
                            .order('badge_id, count DESC, recept_user_id')
    end
  end

  def summary_value_send
    if params[:summary_form] == nil
      # 検索未入力時（初回表示時）
      @form = SummaryForm.new
    else
      # 検索欄入力時
      set_search_form_params
      
      # マスター情報関連取得
      set_master_data
      
      value_badge_ids = Badge.select(:id).where(optionflg: false)

      @sentbadgeposts = Badgepost.select(:sent_user_id, "COUNT(*) AS count")
                            .where('created_at >= ?', @form.summary_start_date)
                            .where('created_at <= ?', @form.summary_end_date)
                            .where(badge_id: value_badge_ids)
                            .group(:sent_user_id).order('count DESC, sent_user_id')
    end
  end

  def summary_value_bumon_send
    if params[:summary_form] == nil
      # 検索未入力時（初回表示時）
      @form = SummaryForm.new
    else
      # 検索欄入力時
      set_search_form_params
      
      # マスター情報関連取得
      set_master_data
      
      value_badge_ids = Badge.select(:id).where(optionflg: false)
      
      userjoin = User.arel_table
      badgepostjoin = Badgepost.arel_table
      join_condition = userjoin.join(badgepostjoin, Arel::Nodes::OuterJoin)
                  .on(userjoin[:id].eq(badgepostjoin[:sent_user_id])).join_sources
      
      @sentbadgeposts = User.joins(join_condition).group(:bumon_id)
                .select(userjoin[:bumon_id], userjoin[:bumon_id].count.as('count'))
                      .where(badgepostjoin[:created_at].gteq @form.summary_start_date)
                      .where(badgepostjoin[:created_at].lteq @form.summary_end_date)
                      .where(badgepostjoin[:badge_id].in(value_badge_ids.map{|badge| badge.id }))
                      .order('count DESC').order(:bumon_id)
    end
  end

  private
    def find_params
      params.require(:summary_form).permit(:summary_start_date, :summary_end_date)
    end
    
    def set_search_form_params
      summary_start_date = Time.zone.local(params[:summary_form]["summary_start_date(1i)"].to_i,
                            params[:summary_form]["summary_start_date(2i)"].to_i,
                            params[:summary_form]["summary_start_date(3i)"].to_i, 0, 0)
      summary_end_date = Time.zone.local(params[:summary_form]["summary_end_date(1i)"].to_i,
                            params[:summary_form]["summary_end_date(2i)"].to_i,
                            params[:summary_form]["summary_end_date(3i)"].to_i, 23, 59)
      @form = SummaryForm.new
      @form.summary_start_date = summary_start_date
      @form.summary_end_date = summary_end_date
    end

    def set_master_data
      # まず、ユーザーをすべて取得（ユーザーと部門名を取得）
      @users = User.all
      @userinfo_hash = get_user_hash(@users)
      
      # 辞書用にバッジ情報を取得
      badges = Badge.where(activeflg: true)
      badges.each do |badge|
        if badge.optionflg
          badge.name = "【2】" + badge.outputnumber.to_s + "." + badge.name
        else
          badge.name = "【1】" + badge.outputnumber.to_s + "." + badge.name
        end
      end
      @badgename_hash = get_name_hash(badges)
      
      # 辞書用に部門情報を取得
      bumons = Bumon.where(activeflg: true)
      @bumonname_hash = get_name_hash(bumons)
    end

    def get_user_hash(users)
      results = users.map{|user| [user.id, user]}
      Hash[results]
    end

    def get_name_hash(objects)
      results = objects.map{|object| [object.id, object.name]}
      Hash[results]
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/adminpage.html.haml
- provide(:title, '管理者用')
%h1 管理者用ページ
= link_to "ユーザー登録", signup_path
%br/
%br/
= link_to "ユーザー一覧", users_full_index_path
%br/
%br/
= link_to "バッジ作成", new_badge_path
%br/
%br/
= link_to "バッジ一覧", badges_path
%br/
%br/
= link_to "部門作成", new_bumon_path
%br/
%br/
= link_to "部門一覧", bumons_path
%br/
%br/
= link_to "文言作成", new_mongon_path
%br/
%br/
= link_to "文言一覧", mongons_path
%br/
%br/
= link_to "（送受信）ピボットテーブル用集計", summary_path
%br/
%br/
= link_to "（受信）バッジ別ユーザー別集計", summary_recept_badge_user_path
%br/
%br/
= link_to "（送信）バリューバッジユーザー別集計", summary_value_send_path
%br/
%br/
= link_to "（送信）バリューバッジ部門別集計", summary_value_bumon_send_path
%br/
%br/
= link_to "みんなが贈ったバッジ", badgeposts_sending_all_path
%br/
%br/

app/views/static_pages/help.html.haml
- provide(:title, 'ヘルプ')
- if logged_in? && logged_in_adminuser?
  = link_to "管理者メニュー", adminpage_path
%h1 ヘルプ
%h3 使い方ガイド
%ol
  %li
    ヘッダーか、プロフィールページなどにある「
    %span.minismile>= image_tag asset_path "smile.png"
    バッジを贈る！！」をクリックします。
  %li バッジを贈りたいメンバーをクリックします。
  %li
    相手に贈りたいバッジをクリックします。#{image_tag asset_path "check_small.png"}がついているバッジが選択されたバッジです。
  %li 相手に贈りたいメッセージを書いて、「バッジを贈る！！」ボタンを押して完了です。

app/views/static_pages/home.html.haml
= render 'sessions/new_form'

app/views/static_pages/login_top.html.haml
- if logged_in?
  = render 'shared/user_info'
- else
  = render 'sessions/new_form'

app/views/static_pages/ranking.html.haml
- provide(:title, '部門別ランキング')
%h3.center_mini_device
  = link_to users_path, :class => "badge_send_button_top" do
    %span.minismile= image_tag asset_path "smile.png"
    バッジを贈る！！
%h1 贈ったバッジランキング（今月）
.container-fluid
  .row
    .col-sm-2
    .col-sm-10
      - if @badgeposts.present?
        %ul.ranking
          - ranking_count = 1
          - @badgeposts.each do |badgepost|
            %li
              %span.rank
                = ranking_count.to_s + " 位"
              - ranking_count += 1
              .bumon_name= @bumonname_hash[badgepost.bumon_id] if @bumonname_hash.has_key?(badgepost.bumon_id)
              %span.badge_count
                = badgepost.cnt
                個
            %br/
            %br/
            %br/

app/views/static_pages/summary.html.haml
- provide(:title, '集計')
.one_column_container
  .summary
    %h2 ピボットテーブル用集計
    = form_for @form, url: summary_path, method: :get do |f|
      %div{:style => "display:inline-flex"}
        = f.date_select :summary_start_date
        ～
        \#{f.date_select :summary_end_date}
        %p= f.submit '集計実行', class: "btn btn-success", data: { disable_with: "集計中..."}
    %br/
    - if !@users.nil?
      - sent_user_set_id_list = Array.new
      - recept_user_set_id_list = Array.new
      %table.table
        %tr{:bgcolor => "green"}
          %th
            %font{:color => "white"} 送受信区分
          %th
            %font{:color => "white"} ユーザー名
          %th
            %font{:color => "white"} 部門名
          %th
            %font{:color => "white"} バッジ名
          %th
            %font{:color => "white"} 年月
          %th
            %font.pull-right{:color => "white"} バッジ数
        - @sentbadgeposts.each do |sentbadgepost|
          %tr
            %td 送信
            - user_info = @userinfo_hash[sentbadgepost.sent_user_id] if @userinfo_hash.has_key?(sentbadgepost.sent_user_id)
            - if user_info.nil?
              %td
            - else
              %td
                - if user_info.activeflg?
                  / 有効なユーザーで、セット済みユーザーIDリストにまだなければセットする。
                  - sent_user_set_id_list.push(sentbadgepost.sent_user_id) if !sent_user_set_id_list.include?(sentbadgepost.sent_user_id)
                - else
                  【無効】
                = user_info.name
            - if user_info.nil?
              %td
            - else
              %td= @bumonname_hash.has_key?(user_info.bumon_id)? @bumonname_hash[user_info.bumon_id] : ""
            %td= @badgename_hash.has_key?(sentbadgepost.badge_id)? @badgename_hash[sentbadgepost.badge_id] : ""
            %td= sentbadgepost.create_month
            %td
              .pull-right= sentbadgepost.count
        - @users.each do |user|
          - next if (!user.activeflg || sent_user_set_id_list.include?(user.id))
          %tr
            %td 送信
            %td= user.name
            %td= user.bumon.name
            %td
            %td
            %td
              .pull-right 0
        - @receptbadgeposts.each do |receptbadgepost|
          %tr
            %td 受信
            - user_info = @userinfo_hash[receptbadgepost.recept_user_id] if @userinfo_hash.has_key?(receptbadgepost.recept_user_id)
            - if user_info.nil?
              %td
            - else
              %td
                - if user_info.activeflg?
                  / 有効なユーザーで、セット済みユーザーIDリストにまだなければセットする。
                  - recept_user_set_id_list.push(receptbadgepost.recept_user_id) if !recept_user_set_id_list.include?(receptbadgepost.recept_user_id)
                - else
                  【無効】
                = user_info.name
            - if user_info.nil?
              %td
            - else
              %td= @bumonname_hash.has_key?(user_info.bumon_id)? @bumonname_hash[user_info.bumon_id] : ""
            %td= @badgename_hash.has_key?(receptbadgepost.badge_id)? @badgename_hash[receptbadgepost.badge_id] : ""
            %td= receptbadgepost.create_month
            %td
              .pull-right= receptbadgepost.count
        - @users.each do |user|
          - next if (!user.activeflg || recept_user_set_id_list.include?(user.id))
          %tr
            %td 受信
            %td= user.name
            %td= user.bumon.name
            %td
            %td
            %td
              .pull-right 0

app/views/static_pages/summary_recept_badge_user.html.haml
- provide(:title, '（受信）バッジ別ユーザー別集計')
.one_column_container_large
  .summary
    %h2 （受信）バッジ別ユーザー別集計
    = form_for @form, url: summary_recept_badge_user_path, method: :get do |f|
      %div{:style => "display:inline-flex"}
        = f.date_select :summary_start_date
        ～
        \#{f.date_select :summary_end_date}
        %p= f.submit '集計実行', class: "btn btn-success", data: { disable_with: "集計中..."}
    %br/
    - if !@users.nil?
      - zenkai_badge_id = ""
      %table.table
        %tr{:bgcolor => "green"}
          %th
            %font{:color => "white"} バッジ名
          %th
            %font{:color => "white"} 部門名
          %th
            %font{:color => "white"} ユーザー名
          %th
            %font.pull-right{:color => "white"} バッジ数
        - @receptbadgeposts.each do |receptbadgepost|
          %tr
            %td
              - unless zenkai_badge_id == receptbadgepost.badge_id
                = @badgename_hash.has_key?(receptbadgepost.badge_id)? @badgename_hash[receptbadgepost.badge_id] : ""
                - zenkai_badge_id = receptbadgepost.badge_id
            - user_info = @userinfo_hash[receptbadgepost.recept_user_id] if @userinfo_hash.has_key?(receptbadgepost.recept_user_id)
            - if user_info.nil?
              %td
            - else
              %td= @bumonname_hash.has_key?(user_info.bumon_id)? @bumonname_hash[user_info.bumon_id] : ""
            - if user_info.nil?
              %td
            - else
              %td
                - unless user_info.activeflg?
                  【無効】
                = user_info.name
            %td
              .pull-right= receptbadgepost.count

app/views/static_pages/summary_value.html.haml
- provide(:title, 'バリューバッジ集計')
.summary
  %h2 もらったバリューバッジ集計
  = form_for @form, url: summary_value_path, method: :get do |f|
    %div{:style => "display:inline-flex"}
      = f.date_select :summary_start_date
      ～
      \#{f.date_select :summary_end_date}
      %p= f.submit '集計実行', class: "btn btn-success", data: { disable_with: "集計中..."}
  %br/
  - if !@users.nil?
    - zenkai_badge_id = ""
    %table{:border => ""}
      %tr{:bgcolor => "green"}
        %th
          %font{:color => "white"} バッジ名
        %th
          %font{:color => "white"} 部門名
        %th
          %font{:color => "white"} ユーザー名
        %th
          %font{:color => "white"} バッジ数
      - @receptbadgeposts.each do |receptbadgepost|
        %tr
          %td
            - unless zenkai_badge_id == receptbadgepost.badge_id
              = @badgename_hash.has_key?(receptbadgepost.badge_id)? @badgename_hash[receptbadgepost.badge_id] : ""
              - zenkai_badge_id = receptbadgepost.badge_id
          - user_info = @userinfo_hash[receptbadgepost.recept_user_id] if @userinfo_hash.has_key?(receptbadgepost.recept_user_id)
          - if user_info.nil?
            %td
          - else
            %td= @bumonname_hash.has_key?(user_info.bumon_id)? @bumonname_hash[user_info.bumon_id] : ""
          - if user_info.nil?
            %td
          - else
            %td
              - unless user_info.activeflg?
                【無効】
              = user_info.name
          %td= receptbadgepost.count

app/views/static_pages/summary_value_bumon_send.html.haml
- provide(:title, '（送信）バリューバッジ部門別集計')
.one_column_container
  .summary
    %h2 （送信）バリューバッジ部門別集計
    = form_for @form, url: summary_value_bumon_send_path, method: :get do |f|
      %div{:style => "display:inline-flex"}
        = f.date_select :summary_start_date
        ～
        \#{f.date_select :summary_end_date}
        %p= f.submit '集計実行', class: "btn btn-success", data: { disable_with: "集計中..."}
    %br/
    - if !@users.nil?
      .one_column_container_mini
        %table.table
          %tr{:bgcolor => "green"}
            %th
              %font{:color => "white"} 部門名
            %th
              %font.pull-right{:color => "white"} バッジ数
          - @sentbadgeposts.each do |sentbadgepost|
            %tr
              %td= @bumonname_hash.has_key?(sentbadgepost.bumon_id)? @bumonname_hash[sentbadgepost.bumon_id] : ""
              %td
                .pull-right= sentbadgepost.count

app/views/static_pages/summary_value_send.html.haml
- provide(:title, '（送信）バリューバッジユーザー別集計')
.one_column_container
  .summary
    %h2 （送信）バリューバッジユーザー別集計
    = form_for @form, url: summary_value_send_path, method: :get do |f|
      %div{:style => "display:inline-flex"}
        = f.date_select :summary_start_date
        ～
        \#{f.date_select :summary_end_date}
        %p= f.submit '集計実行', class: "btn btn-success", data: { disable_with: "集計中..."}
    %br/
    - if !@users.nil?
      .one_column_container_medium
        %table.table
          %tr{:bgcolor => "green"}
            %th
              %font{:color => "white"} 部門名
            %th
              %font{:color => "white"} ユーザー名
            %th
              %font.pull-right{:color => "white"} バッジ数
          - @sentbadgeposts.each do |sentbadgepost|
            %tr
              - user_info = @userinfo_hash[sentbadgepost.sent_user_id] if @userinfo_hash.has_key?(sentbadgepost.sent_user_id)
              - if user_info.nil?
                %td
              - else
                %td= @bumonname_hash.has_key?(user_info.bumon_id)? @bumonname_hash[user_info.bumon_id] : ""
              - if user_info.nil?
                %td
              - else
                %td
                  - unless user_info.activeflg?
                    【無効】
                  = user_info.name
              %td
                .pull-right= sentbadgepost.count