config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'signup',  to: 'users#new'
  get 'login_top' => 'static_pages#login_top'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get    'adminpage'   => 'static_pages#adminpage'
  get    'help'   => 'static_pages#help'
  get    'ranking' => 'static_pages#ranking'
  get    'summary' => 'static_pages#summary'
  get    'summary_recept_badge_user' => 'static_pages#summary_recept_badge_user'
  get    'summary_value_send' => 'static_pages#summary_value_send'
  get    'summary_value_bumon_send' => 'static_pages#summary_value_bumon_send'

  get 'badgeposts/recepting'
  get 'badgeposts/sending'
  get 'badgeposts/sending_all'
  get 'users/full_index'

  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :bumons
  resources :sessions, only: [:new, :create, :destroy]
  resources :badges
  resources :badgeposts
  resources :mongons
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :reset_token
  # 画像アップロード
  mount_uploader :image, ImageUploader

  before_save { self.email = email.downcase }

  validates :bumon, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  VALID_KANANAME_REGEX = /\A[\p{Hiragana}]+\z/
  validates :kananame, presence: true, length: { maximum: 50 },
                    format: { with: VALID_KANANAME_REGEX }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password,
    :length => { :minimum => 8, :if => :validate_password? },
    :confirmation => { :if => :validate_password? }
  validates :nickname, length: { maximum: 15 }
  validates :myjob, length: { maximum: 255 }
  validates :myword, length: { maximum: 255 }
  validates :hobby, length: { maximum: 255 }
  validates :message, length: { maximum: 20 }

  
  belongs_to :bumon, class_name: "Bumon"
  has_many :sent_badgeposts, :class_name => "Badgepost", :foreign_key => "sent_user_id"
  has_many :recept_badgeposts, :class_name => "Badgepost", :foreign_key => "recept_user_id"
  

  # フィードには、自分のささやきと、自分がフォローしているユーザーのつぶやきを表示（取得）
  def feed_badgeposts
    Badgepost.where(recept_user_id: [self.id])
  end
  
  # 与えられた文字列のハッシュ値を返す 
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  # ユーザーログインを破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    # パスワードの有効期限は2時間とする
    reset_sent_at < 2.hours.ago
  end
  
  private
  
    def validate_password?
      password.present? || password_confirmation.present?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :find, :show,
                                        :edit, :edit_password, :update]
  before_action :logged_in_adminuser, only: [:full_index, :new, :create ]
  before_action :editable_user,   only: [:edit, :update]

  
  def index
    # カレントユーザーを表示しない
    @users = get_index_users(false, params[:initial_letter], params[:bumon_id])
  end
  
  
  def full_index
    # カレントユーザー含め全ユーザーを表示する
    @users = get_index_users(true, params[:initial_letter], params[:bumon_id])
  end
  
  
  def find
    @form = UserFindForm.new
  end
  
  
  def show
    @user = User.find(params[:id])
    
    # 30日間に獲得したバッジのグラフ
    @graph_recept30days = get_graph(@user.id, "", "30DAYS_RECEPT")
   
    # 今までに獲得したバッジのグラフ
    @graph_recept = get_graph(@user.id, "", "ALL_RECEPT")
    
    # 今までに贈ったバッジのグラフ
    @graph_sent = get_graph(@user.id, "", "ALL_SENT")
  end
  
  
  def new
    @user = User.new
  end
  

  def edit
    @user = User.find(params[:id])
  end
  
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザー「" + @user.name + "」を登録しました！"
      redirect_to adminpage_path
    else
      render 'new'
    end
  end
  
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      # 保存に成功した場合はプロフィールページへリダイレクト
      flash[:success] = "プロフィールを編集しました。"
      redirect_to @user
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  

  private
    def user_params
      params.require(:user)
        .permit(:activeflg, :bumon_id, :name, :kananame, :nickname, :adminflg,
              :email, :password, :password_confirmation,
              :myjob, :myword, :hobby, :message,
              :image, :remove_image, :image_cache)
    end
    
    def find_params
      params.require(:user_find_form).permit(:searchword)
    end
    
    def get_index_users(display_current_user, initial_letter, bumon_id)
      @bumons = Bumon.where(activeflg: true).order(:outputnumber)
      
      if params[:user_find_form] == nil
        # 検索未入力時（初回表示時）
        @form = UserFindForm.new
        # 自分以外のユーザーを取得する。
        # ソート：カナ（昇順）
        t = User.arel_table

        if display_current_user
          if initial_letter.present?
            @users = User.paginate(page: params[:page])
                          .where(t[:kananame].matches(initial_letter + '%'))
          elsif bumon_id.present?
            @users = User.paginate(page: params[:page])
                          .where(bumon_id: bumon_id)
            # 30日間に獲得したバッジのグラフ
            @graph_recept30days = get_graph("", bumon_id, "30DAYS_RECEPT")
          else
            @users = User.paginate(page: params[:page])
          end
        else
          if initial_letter.present?
            @users = User.paginate(page: params[:page])
                    .where('id <> ?', current_user.id)
                    .where(activeflg: true)
                    .where(t[:kananame].matches(initial_letter + '%'))
          elsif bumon_id.present?
            @users = User.paginate(page: params[:page])
                    .where('id <> ?', current_user.id)
                    .where(activeflg: true)
                    .where(bumon_id: bumon_id)
            # 30日間に獲得したバッジのグラフ
            @graph_recept30days = get_graph("", bumon_id, "30DAYS_RECEPT")
          else
            @users = User.paginate(page: params[:page])
                    .where('id <> ?', current_user.id)
                    .where(activeflg: true)
          end
        end
        
        if Rails.env == 'production'
          @users.order('kananame COLLATE "C"')
        elsif Rails.env == 'development' or Rails.env == 'test'
          @users.order(:kananame)
        end
      else
        # 検索欄入力時
        @form = UserFindForm.new(find_params)
        @searchword = @form.searchword.gsub("　", " ")
        t = User.arel_table
        
        # 自分以外のユーザーを取得する。
        # ソート：カナ（昇順）
        @users = User.paginate(page: params[:page])
                      .where(t[:name].matches('%' + @searchword + '%')
                        .or(t[:kananame].matches('%' + @searchword + '%'))
                        .or(t[:email].matches('%' + @searchword + '%')))
        
        if display_current_user
          @users = User.paginate(page: params[:page])
                    .where(t[:name].matches('%' + @searchword + '%')
                      .or(t[:kananame].matches('%' + @searchword + '%'))
                      .or(t[:email].matches('%' + @searchword + '%')))
        else
          @users = User.paginate(page: params[:page])
                      .where('id <> ?', current_user.id)
                      .where(t[:activeflg].eq(true))
                      .where(t[:name].matches('%' + @searchword + '%')
                        .or(t[:kananame].matches('%' + @searchword + '%'))
                        .or(t[:email].matches('%' + @searchword + '%')))
        end
  
        if Rails.env == 'production'
          @users.order('kananame COLLATE "C"')
        elsif Rails.env == 'development' or Rails.env == 'test'
          @users.order(:kananame)
        end
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
  def get_graph(user_id, bumon_id, type)
      # グラフインスタンス取得
      
      badgejoin = Badge.arel_table
      badgepostjoin = Badgepost.arel_table
      
      join_condition = badgejoin.join(badgepostjoin, Arel::Nodes::OuterJoin)
                .on(badgejoin[:id].eq(badgepostjoin[:badge_id])).join_sources
      
      if type == "30DAYS_RECEPT"
        if bumon_id == ""
          @badgeposts = Badge.joins(join_condition).group(:id, :name, :image, :outputnumber)
              .select(badgejoin[:id], badgejoin[:name], badgejoin[:image], badgejoin[:outputnumber], badgejoin[:id].count.as('cnt'))
                    .where(badgepostjoin[:recept_user_id].eq(user_id))
                    .where(badgepostjoin[:created_at].gt 30.days.ago)
                    .order('cnt DESC').order(badgejoin[:outputnumber])
        else
          taisyou_users = User.where(bumon_id: bumon_id)
          taisyou_user_ids = Array.new
          taisyou_users.each do |user|
            taisyou_user_ids.push(user.id)
          end
          @badgeposts = Badge.joins(join_condition).group(:id, :name, :image, :outputnumber)
              .select(badgejoin[:id], badgejoin[:name], badgejoin[:image], badgejoin[:outputnumber], badgejoin[:id].count.as('cnt'))
                    .where(badgepostjoin[:recept_user_id].in(taisyou_user_ids))
                    .where(badgepostjoin[:created_at].gt 30.days.ago)
                    .order('cnt DESC').order(badgejoin[:outputnumber])
        end
      elsif type == "ALL_RECEPT"
        @badgeposts = Badge.joins(join_condition).group(:id, :name, :image, :outputnumber)
              .select(badgejoin[:id], badgejoin[:name], badgejoin[:image], badgejoin[:outputnumber], badgejoin[:id].count.as('cnt'))
                    .where(badgepostjoin[:recept_user_id].eq(user_id))
                    .order('cnt DESC').order(badgejoin[:outputnumber])
      else
        @badgeposts = Badge.joins(join_condition).group(:id, :name, :image, :outputnumber)
              .select(badgejoin[:id], badgejoin[:name], badgejoin[:image], badgejoin[:outputnumber], badgejoin[:id].count.as('cnt'))
                    .where(badgepostjoin[:sent_user_id].eq(user_id))
                    .order('cnt DESC').order(badgejoin[:outputnumber])
      end
  
      data = Array.new
      
      if @badgeposts != []
        badges = Badge.where(activeflg: true)
        badges.each do |badge|
          badgesetflg = false
          @badgeposts.each do |badgepost|
            if badge.name == badgepost.name
              data.push([badgepost.name, badgepost.cnt])
              badgesetflg = true
            end
          end
          data.push([badge.name, 0]) unless badgesetflg
        end
      end

      @graph = LazyHighCharts::HighChart.new('graph') do |f|
        # グラフタイトル
        if type == "30DAYS_RECEPT"
          if bumon_id == ""
            f.title(text: '30日間に獲得したバッジバランス')
          else
            f.title(text: Bumon.find(bumon_id).name + "が30日間に獲得したバッジバランス")
          end
        elsif type == "ALL_RECEPT"
          f.title(text: '今までに獲得したバッジバランス')
        else
          f.title(text: '今までに贈ったバッジバランス')
        end
        f.series(name: 'バッジ数', data: data, type: 'pie')
      end
  end
end

app/views/users/_badge_send_link.html.haml
%p.badgesendlink
  - if current_user?(user)
    %h3.center_mini_device
      = link_to users_path, :class => "badge_send_button_top" do
        %span.minismile= image_tag asset_path "smile.png"
        バッジを贈る！！
  - else
    %span.username
      %b= user.name
      さんに
    %span.br_mini_device
      %br
      %br
    = link_to new_badgepost_path(recept_user_id: user.id), :class => "badge_send_button_profile" do
      %span.minismile
        = image_tag asset_path "smile.png"
        バッジを贈る！！

app/views/users/_partial_bumon_search.html.haml
.user_initial_dropdown
  %span.dropdown
    %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
      部門で絞る
      %span.caret
    %ul.dropdown-menu
      - @bumons.each do |bumon|
        %li= link_to(bumon.name, :action => @index_action_name, :bumon_id => bumon.id)

app/views/users/_partial_index.html.haml
- provide(:title, '全メンバー')
= javascript_include_tag 'balloon'
.userindex
  - if adminModeFlg
    .search
      = form_for @form, url: users_full_index_path, method: :get do |f|
        .searchbox{:style => "display:inline-flex"}
          = f.text_field :searchword, placeholder: "名前、かな、アドレス", required: true
          = f.submit '検索する', class: "btn btn-success", data: { disable_with: "検索中..."}
    %h4.center= link_to "全ユーザーを表示", users_full_index_path
    %h1 プロフィールを編集するメンバーを選んでね！！
    - @index_action_name = "full_index"
  - else
    .search
      = form_for @form, url: users_path, method: :get do |f|
        .searchbox{:style => "display:inline-flex"}
          = f.text_field :searchword, placeholder: "名前、かな、アドレス", required: true
          = f.submit '検索する', class: "btn btn-success", data: { disable_with: "検索中..."}
    %h4.center= link_to "全ユーザーを表示", users_path
    %h1 バッジを贈るメンバーを選んでね！！
    - @index_action_name = "index"
  = render 'users/partial_bumon_search'
  %br/
  = render 'users/partial_initial_letter'
  .will_paginate= will_paginate
  %h2
    全メンバー (#{@users.count})
  .container-fluid
    .row
      %section
        - if @users.any?
          %ol.users
            - @users.each do |user|
              .col-md-4.col-sm-6
                %li
                  - if adminModeFlg == true
                    / 管理モード時
                    %span.gravatar{:title => "#{user.message}"}
                      - if user.image?
                        .middleimage{:style => "background-image: url(#{user.image.url});"}
                      - else
                        .middleimage{:style => "background-image: url(#{asset_path "user_noimage.gif"});"}
                    %span.user
                      %b= user.name
                    %br/
                    %span= user.bumon.name
                    %br/
                    = user.activeflg ? "" : "【無効】"
                    = user.adminflg ? "【管理者】" : ""
                    = link_to "プロフィール編集", edit_user_path(user.id)
                  - else
                    / バッジ送付先選択画面時
                    .gravatar{:title => "#{user.message}"}
                      - if user.image?
                        .middleimage{:style => "background-image: url(#{user.image.url});"}
                          = link_to image_tag('empty.gif'), new_badgepost_path(recept_user_id: user.id)
                      - else
                        .middleimage{:style => "background-image: url(#{asset_path "user_noimage.gif"});"}
                          = link_to image_tag('empty.gif'), new_badgepost_path(recept_user_id: user.id)
                    .user
                      .badgesendlink
                        %b.username= user.name
                        さんに
                      = link_to new_badgepost_path(recept_user_id: user.id), :class => "badge_send_button_user_index" do
                        %span.minismile= image_tag asset_path "smile.png"
                        バッジを贈る！！
                      .bumon_name
                        = user.bumon.name
                      .profile
                        %i.fa.fa-user.fa-fw
                        = link_to "プロフィール", user
                    .clear_both
  .will_paginate= will_paginate
- if current_user.sent_badgeposts.count >= 1
  / 過去30日間に獲得したバッジグラフ表示
  = high_chart("radar", @graph_recept30days) if @graph_recept30days.present?
- elsif @graph_recept30days.present?
  .graph_blank
    %h3 まずはバッジを1個贈ってみよう！
    %h3 この部門がもらったバッジの
    %h3 バランスグラフが表示されるよ！
:javascript
  // ユーザーの画像に一言メッセージをポップアップ
  $(".gravatar").balloon({ position: "right", offsetX: 0, offsetY: -30, 
                        css: { backgroundColor: '#EEFFFF', color: '#000', opacity: '1' } });

app/views/users/_partial_initial_letter.html.haml
- data = [ ["あ","い","う","え","お"], ["か","き","く","け","こ","が","ぎ","ぐ","げ","ご"], ["さ","し","す","せ","そ","ざ","じ","ず","ぜ","ぞ"], ["た","ち","つ","て","と","だ","ぢ","づ","で","ど"], ["な","に","ぬ","ね","の"], ["は","ひ","ふ","へ","ほ","ば","び","ぶ","べ","ぼ"], ["ま","み","む","め","も"], ["や","ゆ","よ"], ["ら","り","る","れ","ろ"], ["わ","を","ん"] ]
.user_initial_dropdown
  - data.each { |data_gyou|
  %span.dropdown
    %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
      = data_gyou[0]
      行
      %span.caret
    %ul.dropdown-menu
      - data_gyou.each { |d|
      %li= link_to(d, :action => @index_action_name, :initial_letter => d)
      - }
  - }

app/views/users/edit.html.haml
%h1
  = @user.name
= form_for(@user) do |f|
  - if @user.errors.present?
    .alert.alert-danger
      = alert
      %ul
        - @user.errors.full_messages.each do |full_message|
          %li
            = full_message
  .field
    - if @user.image?
      .thumbnail
        = image_tag @user.image.url
    %br/
    = f.label :image
    %br/
    = f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: 'form-control'
    = f.hidden_field :image_cache
  .field
    - if @user.persisted? && @user.image?
      %label
        = f.check_box :remove_image
        画像を削除
    %br/
    %br/
    - if logged_in_adminuser?
      / 管理者なら
      = f.label "ユーザー有効フラグ"
      = f.check_box 'activeflg'
      = f.label "管理者フラグ"
      = f.check_box 'adminflg'
      = f.label "氏名"
      = f.text_field :name, required: true, class: 'form-control'
      = f.label "ふりがな"
      = f.text_field :kananame, required: true, class: 'form-control'
      = f.label "部門名"
      = f.collection_select(:bumon_id, Bumon.all.order(:outputnumber), :id, :name)
      = f.label "メールアドレス"
      = f.email_field :email, class: 'form-control'
    - else
      / 通常ユーザーなら
      %p= f.label "氏名"
      %p= @user.name
      %p= f.label "ふりがな"
      %p= @user.kananame
      %p= f.label "部門名"
      %p= @user.bumon.name
      %p= f.label "メールアドレス"
      %p= @user.email
    = f.label "ニックネーム（15字以内）"
    = f.text_field :nickname, class: 'form-control'
    = f.label "一言メッセージ（20字以内）"
    = f.text_field :message, class: 'form-control'
    = f.label "こんな仕事をしています（255字以内）"
    = f.text_area :myjob, :size => "10x8", class: 'form-control'
    = f.label "好きな言葉・座右の銘・マイルール（255字以内）"
    = f.text_area :myword, :size => "10x8", class: 'form-control'
    = f.label "趣味（255字以内）"
    = f.text_area :hobby, :size => "10x8", class: 'form-control'
    = f.label "パスワード：8文字以上（変更する場合は入力してください）"
    = f.password_field :password, class: 'form-control'
    = f.label :password_confirmation, "パスワード（確認）：8文字以上"
    = f.password_field :password_confirmation, class: 'form-control'
    = f.submit "プロフィールを更新", class: "btn btn-sm btn-primary"
    :javascript
      $('#user_image').bind('change', function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 2) {
          alert('ファイルの上限は2MBまでです。容量の小さいファイルを選択してください。');
        }
      });

app/views/users/full_index.html.haml
= render 'users/partial_index', adminModeFlg: true

app/views/users/index.html.haml
= render 'users/partial_index', adminModeFlg: false

app/views/users/new.html.haml
- provide(:title, '会員登録')
%h1 会員登録
.row
  .col-md-6.col-md-offset-3
    = form_for(@user) do |f|
      = render 'shared/error_messages', object: f.object
      = f.label "部門名"
      = f.collection_select(:bumon_id, Bumon.where(activeflg: true).order(:outputnumber), :id, :name, {:class => "form-control"})
      = f.label "氏名"
      = f.text_field :name, :placeholder => "姓名の間は全角スペースを空けてください", class: 'form-control'
      = f.label "ふりがな"
      = f.text_field :kananame, :placeholder => "スペースを空けず連続して入力してください", class: 'form-control'
      = f.label "メールアドレス"
      = f.email_field :email, :placeholder => "...@" + ENV["EMAIL_DOMAIN"], class: 'form-control'
      = f.label "パスワード：8文字以上"
      = f.password_field :password, class: 'form-control'
      = f.label :password_confirmation, "パスワード（確認）：8文字以上"
      = f.password_field :password_confirmation, class: 'form-control'
      = f.submit "会員登録実行！", class: "btn btn-large btn-primary"

app/views/users/show.html.haml
.profile_show
  = render 'users/badge_send_link', user: @user
  .users
    - if current_user?(@user) || logged_in_adminuser?
      / 自分自身か、管理者ユーザーは編集OK
      .edit_profile
        %i.fa.fa-cog.fa-fw
        = link_to "プロフィール・パスワードの編集" , edit_user_path(@user)
  .row
    .col-md-4
      .name_block
        %p.bumon_name= @user.bumon.name
        %p.kananame= @user.kananame
        %p.name
          %b= @user.name
        %p.nickname
          ニックネーム：
          %b
            %span.nicknamevalue= @user.nickname
        %p.email
          メールアドレス：#{@user.email}
    .col-md-4
      %section.user_info
        %p.gravatar
          - if @user.image?
            .largeimage{:style => "background-image: url(#{@user.image.url});"}
              - unless current_user?(@user)
                = link_to image_tag('empty.gif'), new_badgepost_path(recept_user_id: @user.id)
          - else
            .largeimage{:style => "background-image: url(#{asset_path "user_noimage.gif"});"}
              - unless current_user?(@user)
                = link_to image_tag('empty.gif'), new_badgepost_path(recept_user_id: @user.id)
        .arrow_box
          %b= @user.message
      .myjob
        %p
          %b こんな仕事をしています
        %hr/
        %span= simple_format(h(@user.myjob))
    .col-md-4
      .myword
        %p
          %b 好きな言葉・座右の銘・マイルール
        %hr/
        %span= simple_format(h(@user.myword))
      .hobby
        %p
          %b 趣味
        %hr/
        %span= simple_format(h(@user.hobby))
  %br/
  - if current_user.sent_badgeposts.count >= 1
    / 過去30日間に獲得したバッジグラフ表示
    = high_chart("radar1", @graph_recept30days)
    / 今までに獲得したバッジグラフ表示
    = high_chart("radar2", @graph_recept)
    / 今までに贈ったバッジグラフ表示
    = high_chart("radar3", @graph_sent)
  - else
    .graph_blank
      %h3 まずはバッジを1個贈ってみよう！
      %h3 やり取りしたバッジのバランスグラフ
      %h3 が表示されるよ！
  = render 'users/badge_send_link', user: @user