config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'signup',  to: 'users#new'
  get 'login_top' => 'static_pages#login_top'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get    'adminpage'   => 'static_pages#adminpage'
  get    'help'   => 'static_pages#help'
  get    'ranking' => 'static_pages#ranking'
  get    'summary' => 'static_pages#summary'
  get    'summary_recept_badge_user' => 'static_pages#summary_recept_badge_user'
  get    'summary_value_send' => 'static_pages#summary_value_send'
  get    'summary_value_bumon_send' => 'static_pages#summary_value_bumon_send'

  get 'badgeposts/recepting'
  get 'badgeposts/sending'
  get 'badgeposts/sending_all'
  get 'users/full_index'

  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :bumons
  resources :sessions, only: [:new, :create, :destroy]
  resources :badges
  resources :badgeposts
  resources :mongons
end

app/views/layouts/_footer.html.haml
%footer
  .copyright
    © #{Date.today.year} SMILE Badge.

app/views/layouts/_header.html.haml
%body
  %header
    %nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-inner
          .navbar-header
            %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to root_path do
              %span#logo
                SMILE Badge!!
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav.navbar-right
              - unless logged_in?
                - if !User.exists?(adminflg: true)
                  %li= link_to "管理者", adminpage_path
                %li
                  = link_to login_path do
                    %i.fa.fa-sign-in
                    ログイン
                %li
                  = link_to help_path do
                    %i.fa.fa-question-circle
                    ヘルプ
              - else
                %li
                  = link_to users_path, :class => "badge_send_button_header" do
                    %span.minismile= image_tag asset_path "smile.png"
                    バッジを贈る！！
                %li
                  = link_to badgeposts_sending_path do
                    %i.fa.fa-paper-plane-o
                    贈った
                %li
                  = link_to badgeposts_recepting_path do
                    %i.fa.fa-gift
                    もらった
                %li.dropdown
                  %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                    .clearfix
                      .user_name.pull-right
                        = current_user.name
                        %span.caret
                      .gravatar.pull-right
                        .smallimage
                          - if current_user.image?
                            = image_tag current_user.image.url
                          - else
                            = image_tag 'user_noimage.gif'
                  %ul.dropdown-menu
                    %li
                      = link_to current_user do
                        %i.fa.fa-user.fa-fw
                        マイページ
                    %li
                      = link_to edit_user_path(current_user) do
                        %i.fa.fa-cog.fa-fw
                        設定
                    %li.divider{:role => "separator"}
                    %li
                      = link_to help_path do
                        %i.fa.fa-question-circle
                        ヘルプ
                        - if logged_in? && logged_in_adminuser?
                          = "・管理"
                    %li.divider{:role => "separator"}
                    %li
                      = link_to logout_path, method: "delete" do
                        %i.fa.fa-sign-out
                        ログアウト

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width", :name => "viewport"}/
    %title SMILE Badge!!
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = favicon_link_tag
    = analytics_init if GA.tracker != GoogleAnalytics::PLACEHOLDER_TRACKER
  %body
    .body_back_image
      .layerTransparent
        = render 'layouts/header'
        .container
          - flash.each do |message_type, message|
            = content_tag(:div, message, class: "alert alert-#{message_type}")
          = yield
        = render partial: "layouts/footer"
    :javascript
      window._pt_lt = new Date().getTime();
      	  window._pt_sp_2 = [];
      	  _pt_sp_2.push('setAccount,4f8b5146');
      	  var _protocol = (("https:" == document.location.protocol) ? " https://" : " http://");
      	  (function() {
      		var atag = document.createElement('script'); atag.type = 'text/javascript'; atag.async = true;
      		atag.src = _protocol + 'js.ptengine.jp/pta.js';
      		var stag = document.createElement('script'); stag.type = 'text/javascript'; stag.async = true;
      		stag.src = _protocol + 'js.ptengine.jp/pts.js';
      		var s = document.getElementsByTagName('script')[0]; 
      		s.parentNode.insertBefore(atag, s);s.parentNode.insertBefore(stag, s);
      	  })();